name: Apply KernelSU Patches

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  apply-patches:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup environment
      run: |
        echo "KERNEL_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        
    - name: Apply patches with error handling
      run: |
        set +e  # Jangan gagal langsung pada error
        
        # Terapkan patch KernelSU
        if [ -f "KernelSU/10_enable_susfs_for_ksu.patch" ]; then
          echo "Menerapkan patch KernelSU..."
          cd KernelSU
          patch -p1 --verbose < 10_enable_susfs_for_ksu.patch
          echo "Status patch KernelSU: $?"
          cd ..
        fi
        
        # Terapkan patch kernel
        if [ -f "50_add_susfs_in_kernel-4.19.patch" ]; then
          echo "Menerapkan patch kernel..."
          patch -p1 --verbose < 50_add_susfs_in_kernel-4.19.patch
          echo "Status patch kernel: $?"
        fi
        
        # Periksa file .rej yang dihasilkan
        echo "File reject yang dihasilkan:"
        find . -name "*.rej" -type f | head -10
        
        set -e  # Kembali ke mode fail-on-error
        
    - name: Handle patch rejects
      run: |
        # Hitung jumlah file .rej
        REJ_COUNT=$(find . -name "*.rej" -type f | wc -l)
        echo "Jumlah file reject: $REJ_COUNT"
        
        if [ "$REJ_COUNT" -gt 0 ]; then
          echo "Peringatan: Beberapa patch gagal diterapkan sepenuhnya"
          echo "File .rej telah dibuat yang menunjukkan bagian yang gagal"
          
          # Simpan file reject sebagai artifact untuk diperiksa
          mkdir -p patch-rejects
          find . -name "*.rej" -exec cp {} patch-rejects/ \;
        fi
        
    - name: Upload patch rejects as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: patch-rejects
        path: patch-rejects/
        
    - name: Commit successful changes
      run: |
        # Hanya commit jika tidak ada file .rej atau kita memutuskan untuk continue
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        
        # Jangan commit file .rej
        find . -name "*.rej" -exec git rm --cached {} \; 2>/dev/null || true
        
        if ! git diff --staged --quiet; then
          git commit -m "Apply KernelSU patches (partial)"
          git push
          echo "Perubahan yang berhasil telah di-push"
        else
          echo "Tidak ada perubahan yang berhasil diterapkan"
        fi
